const ACTION_BUTTONS = [
  { key: "zero", value: 0 },
  { key: "one", value: 1 },
  { key: "two", value: 2 },
  { key: "three", value: 3 },
  { key: "four", value: 4 },
  { key: "five", value: 5 },
  { key: "six", value: 6 },
  { key: "seven", value: 7 },
  { key: "eight", value: 8 },
  { key: "nine", value: 9 },
  { key: "mul", value: "*" },
  { key: "div", value: "/" },
  { key: "minus", value: "-" },
  { key: "plus", value: "+" },
  { key: "dot", value: "." },
  { key: "open", value: "(" },
  { key: "close", value: ")" },
];
